server:
  port: 12100


spring:
  servlet:
    multipart:
      # 单个文件上传的最大值
      max-file-size: 100MB
      # 多个文件上传的总的最大值
      max-request-size: 500MB
  cloud:
    loadbalancer:
      retry:
        # 该参数用来开启重试机制，它默认是关闭的。
        enabled: true
  application:
    name: user-demo


eureka:
  client:
    service-url:
      # 注册中心地址
      defaultZone: http://127.0.0.1:2100/eureka/
  instance:
    # 配置在eureka上status栏显示的信息
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

feign:
  hystrix:
    # 关闭hystrix默认就是关闭，若是设置为true的话一定要记得配置超时的时间，要不到时候可能会导致超时失败，因此最好将此处的熔断机制给去除
    enabled: false
  compression:
    # 开启GZIP的压缩功能以减少HTTP通信的消耗。
    request:
      enabled: true
      # 以下的请求的类型且请求数据的大小超过2048的将为会压缩传输。
      min-request-size: 2048
      mime-types: text/xml,application/xml,application/json
    response:
      enabled: true

ribbon:
  # #请求连接的超时时间。
  ConnectTimeout: 6000
  # 请求处理的超时时间，该超时时间的影响层级大于全局的超时时间,设置了该时间那么，如果调用生产端的时候超过1秒那么就直接调用重试规则，因此若重试次数和切换次数都是为1那么，响应的时间不超过4秒
  ReadTimeout: 60000
  # 对所有操作请求都进行重试。
  OkToRetryOnAllOperations: true
  # 以下重试实现响应EUREKA-PRODUCER的最大次数是 ：（1 + MaxAutoRetries）* （1 + MaxAutoRetriesNextServer）
  # 假设 MaxAutoRetries = 2 ，MaxAutoRetriesNextServer = 4 ，那么最大的重试次数为15次
  # 切换实例的重试次数。
  MaxAutoRetriesNextServer: 1
  # 对当前实例的重试次数。
  MaxAutoRetries: 1